/*
Deployment script for D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF"
:setvar DefaultFilePrefix "D_\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF_"
:setvar DefaultDataPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Rename [dbo].[CongViec].[BatDau] to FromDate';


GO
EXECUTE sp_rename @objname = N'[dbo].[CongViec].[BatDau]', @newname = N'FromDate', @objtype = N'COLUMN';


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Rename [dbo].[CongViec].[KetThuc] to ToDate';


GO
EXECUTE sp_rename @objname = N'[dbo].[CongViec].[KetThuc]', @newname = N'ToDate', @objtype = N'COLUMN';


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Rename [dbo].[CongViec].[ViTri] to ViTriTuyenDung';


GO
EXECUTE sp_rename @objname = N'[dbo].[CongViec].[ViTri]', @newname = N'ViTriTuyenDung', @objtype = N'COLUMN';


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Dropping Foreign Key [dbo].[FK_UngTuyen_CongViec]...';


GO
ALTER TABLE [dbo].[UngTuyen] DROP CONSTRAINT [FK_UngTuyen_CongViec];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
/*
The column [dbo].[CongViec].[KyNangChuyenMon] is being dropped, data loss could occur.

The column [dbo].[CongViec].[KyNangMem] is being dropped, data loss could occur.

The type for column Link in table [dbo].[CongViec] is currently  NVARCHAR (2000) NULL but is being changed to  NVARCHAR (500) NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type  NVARCHAR (500) NULL.
*/
GO
PRINT N'Starting rebuilding table [dbo].[CongViec]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_CongViec] (
    [Id]             INT             NOT NULL,
    [Ten]            NVARCHAR (500)  NULL,
    [Nganh]          NVARCHAR (100)  NULL,
    [ViTriTuyenDung] NVARCHAR (100)  NULL,
    [MucLuong]       DECIMAL (18)    NULL,
    [DiaDiem]        NVARCHAR (255)  NULL,
    [TrinhDoHocVan]  NVARCHAR (255)  NULL,
    [GioiTinh]       NVARCHAR (20)   NULL,
    [LienHe]         NVARCHAR (100)  NULL,
    [MoTa]           NVARCHAR (2000) NULL,
    [QuyenLoi]       NVARCHAR (2000) NULL,
    [NgoaiNgu]       NVARCHAR (2000) NULL,
    [TinHoc]         NVARCHAR (2000) NULL,
    [KinhNghiem]     NVARCHAR (2000) NULL,
    [KyNang]         NVARCHAR (2000) NULL,
    [FromDate]       DATE            NULL,
    [ToDate]         DATE            NULL,
    [TrangThai]      NVARCHAR (50)   NULL,
    [SoLuong]        INT             NULL,
    [Link]           NVARCHAR (500)  NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[CongViec])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_CongViec] ([Id], [Ten], [Nganh], [ViTriTuyenDung], [DiaDiem], [TrinhDoHocVan], [GioiTinh], [LienHe], [MoTa], [QuyenLoi], [NgoaiNgu], [TinHoc], [FromDate], [ToDate], [TrangThai], [SoLuong], [Link])
        SELECT   [Id],
                 [Ten],
                 [Nganh],
                 [ViTriTuyenDung],
                 [DiaDiem],
                 [TrinhDoHocVan],
                 [GioiTinh],
                 [LienHe],
                 [MoTa],
                 [QuyenLoi],
                 [NgoaiNgu],
                 [TinHoc],
                 [FromDate],
                 [ToDate],
                 [TrangThai],
                 [SoLuong],
                 [Link]
        FROM     [dbo].[CongViec]
        ORDER BY [Id] ASC;
    END

DROP TABLE [dbo].[CongViec];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_CongViec]', N'CongViec';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating Foreign Key [dbo].[FK_UngTuyen_CongViec]...';


GO
ALTER TABLE [dbo].[UngTuyen] WITH NOCHECK
    ADD CONSTRAINT [FK_UngTuyen_CongViec] FOREIGN KEY ([CongViecId]) REFERENCES [dbo].[CongViec] ([Id]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF OBJECT_ID(N'tempdb..#tmpErrors') IS NULL
    CREATE TABLE [#tmpErrors] (
        Error INT
    );

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[UngTuyen] WITH CHECK CHECK CONSTRAINT [FK_UngTuyen_CongViec];


GO
PRINT N'Update complete.';


GO
