/*
Deployment script for D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF"
:setvar DefaultFilePrefix "D_\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF_"
:setvar DefaultDataPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Dropping Foreign Key [dbo].[FK_CV_UngVien]...';


GO
ALTER TABLE [dbo].[CV] DROP CONSTRAINT [FK_CV_UngVien];


GO
PRINT N'Starting rebuilding table [dbo].[CongViec]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_CongViec] (
    [Id]             INT             IDENTITY (1, 1) NOT NULL,
    [Ten]            NVARCHAR (500)  NULL,
    [TenCongTy]      NVARCHAR (500)  NULL,
    [Nganh]          NVARCHAR (100)  NULL,
    [ViTriTuyenDung] NVARCHAR (100)  NULL,
    [MucLuong]       DECIMAL (18)    NULL,
    [DiaDiem]        NVARCHAR (255)  NULL,
    [TrinhDoHocVan]  NVARCHAR (255)  NULL,
    [GioiTinh]       NVARCHAR (20)   NULL,
    [LienHe]         NVARCHAR (100)  NULL,
    [MoTa]           NVARCHAR (2000) NULL,
    [QuyenLoi]       NVARCHAR (2000) NULL,
    [NgoaiNgu]       NVARCHAR (2000) NULL,
    [TinHoc]         NVARCHAR (2000) NULL,
    [KinhNghiem]     NVARCHAR (2000) NULL,
    [KyNang]         NVARCHAR (2000) NULL,
    [FromDate]       DATE            NULL,
    [ToDate]         DATE            NULL,
    [TrangThai]      NVARCHAR (50)   NULL,
    [SoLuong]        INT             NULL,
    [Link]           NVARCHAR (500)  NULL,
    [IsDeleted]      BIT             NULL,
    [CreatedTime]    DATE            NULL,
    [UpdatedTime]    DATE            NULL,
    [IdCongTy]       INT             NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[CongViec])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_CongViec] ON;
        INSERT INTO [dbo].[tmp_ms_xx_CongViec] ([Id], [Ten], [TenCongTy], [Nganh], [ViTriTuyenDung], [MucLuong], [DiaDiem], [TrinhDoHocVan], [GioiTinh], [LienHe], [MoTa], [QuyenLoi], [NgoaiNgu], [TinHoc], [KinhNghiem], [KyNang], [FromDate], [ToDate], [TrangThai], [SoLuong], [Link], [IsDeleted], [CreatedTime], [UpdatedTime], [IdCongTy])
        SELECT   [Id],
                 [Ten],
                 [TenCongTy],
                 [Nganh],
                 [ViTriTuyenDung],
                 [MucLuong],
                 [DiaDiem],
                 [TrinhDoHocVan],
                 [GioiTinh],
                 [LienHe],
                 [MoTa],
                 [QuyenLoi],
                 [NgoaiNgu],
                 [TinHoc],
                 [KinhNghiem],
                 [KyNang],
                 [FromDate],
                 [ToDate],
                 [TrangThai],
                 [SoLuong],
                 [Link],
                 [IsDeleted],
                 [CreatedTime],
                 [UpdatedTime],
                 [IdCongTy]
        FROM     [dbo].[CongViec]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_CongViec] OFF;
    END

DROP TABLE [dbo].[CongViec];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_CongViec]', N'CongViec';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[CV]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_CV] (
    [Id]          INT             IDENTITY (1, 1) NOT NULL,
    [Ten]         NVARCHAR (50)   NULL,
    [UngVienId]   INT             NULL,
    [Link]        NVARCHAR (500)  NULL,
    [MoTa]        NVARCHAR (2000) NULL,
    [TrangThai]   NVARCHAR (50)   NULL,
    [NgayTao]     DATETIME        NULL,
    [NgayCapNhat] DATETIME        NULL,
    [IsDeleted]   BIT             NULL,
    [CreatedTime] DATE            NULL,
    [UpdatedTime] DATE            NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[CV])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_CV] ON;
        INSERT INTO [dbo].[tmp_ms_xx_CV] ([Id], [Ten], [UngVienId], [Link], [MoTa], [TrangThai], [NgayTao], [NgayCapNhat], [IsDeleted], [CreatedTime], [UpdatedTime])
        SELECT   [Id],
                 [Ten],
                 [UngVienId],
                 [Link],
                 [MoTa],
                 [TrangThai],
                 [NgayTao],
                 [NgayCapNhat],
                 [IsDeleted],
                 [CreatedTime],
                 [UpdatedTime]
        FROM     [dbo].[CV]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_CV] OFF;
    END

DROP TABLE [dbo].[CV];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_CV]', N'CV';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[Tinh]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Tinh] (
    [Id]          INT           IDENTITY (1, 1) NOT NULL,
    [Code]        NVARCHAR (10) NULL,
    [Ten]         NVARCHAR (50) NULL,
    [TrangThai]   NVARCHAR (20) NULL,
    [IsDeleted]   BIT           NULL,
    [CreatedTime] DATE          NULL,
    [UpdatedTime] DATE          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Tinh])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Tinh] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Tinh] ([Id], [Code], [Ten], [TrangThai], [IsDeleted], [CreatedTime], [UpdatedTime])
        SELECT   [Id],
                 [Code],
                 [Ten],
                 [TrangThai],
                 [IsDeleted],
                 [CreatedTime],
                 [UpdatedTime]
        FROM     [dbo].[Tinh]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Tinh] OFF;
    END

DROP TABLE [dbo].[Tinh];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Tinh]', N'Tinh';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[UngTuyen]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_UngTuyen] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [CongViecId]  INT            NULL,
    [UngVienId]   INT            NULL,
    [CvId]        INT            NULL,
    [TrangThai]   NVARCHAR (50)  NULL,
    [MoTa]        NVARCHAR (200) NULL,
    [IsDeleted]   BIT            NULL,
    [CreatedTime] DATE           NULL,
    [UpdatedTime] DATE           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[UngTuyen])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_UngTuyen] ON;
        INSERT INTO [dbo].[tmp_ms_xx_UngTuyen] ([Id], [CongViecId], [UngVienId], [CvId], [TrangThai], [MoTa], [IsDeleted], [CreatedTime], [UpdatedTime])
        SELECT   [Id],
                 [CongViecId],
                 [UngVienId],
                 [CvId],
                 [TrangThai],
                 [MoTa],
                 [IsDeleted],
                 [CreatedTime],
                 [UpdatedTime]
        FROM     [dbo].[UngTuyen]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_UngTuyen] OFF;
    END

DROP TABLE [dbo].[UngTuyen];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_UngTuyen]', N'UngTuyen';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[UngVien]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_UngVien] (
    [Id]          INT            IDENTITY (1, 1) NOT NULL,
    [HoTen]       NVARCHAR (50)  NULL,
    [NgaySinh]    DATE           NULL,
    [GioiTinh]    NVARCHAR (20)  NULL,
    [DiaChi]      NVARCHAR (100) NULL,
    [SDT]         NVARCHAR (20)  NULL,
    [Email]       NVARCHAR (50)  NULL,
    [ChuyenMon]   NVARCHAR (MAX) NULL,
    [TrangThai]   NVARCHAR (50)  NULL,
    [Avatar]      IMAGE          NULL,
    [IsDeleted]   BIT            NULL,
    [CreatedTime] DATE           NULL,
    [UpdatedTime] DATE           NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[UngVien])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_UngVien] ON;
        INSERT INTO [dbo].[tmp_ms_xx_UngVien] ([Id], [HoTen], [NgaySinh], [GioiTinh], [DiaChi], [SDT], [Email], [ChuyenMon], [TrangThai], [Avatar], [IsDeleted], [CreatedTime], [UpdatedTime])
        SELECT   [Id],
                 [HoTen],
                 [NgaySinh],
                 [GioiTinh],
                 [DiaChi],
                 [SDT],
                 [Email],
                 [ChuyenMon],
                 [TrangThai],
                 [Avatar],
                 [IsDeleted],
                 [CreatedTime],
                 [UpdatedTime]
        FROM     [dbo].[UngVien]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_UngVien] OFF;
    END

DROP TABLE [dbo].[UngVien];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_UngVien]', N'UngVien';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Starting rebuilding table [dbo].[User]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_User] (
    [Id]          INT           IDENTITY (1, 1) NOT NULL,
    [UserName]    NVARCHAR (50) NULL,
    [Password]    NVARCHAR (50) NULL,
    [Email]       NVARCHAR (50) NULL,
    [Status]      NVARCHAR (50) NULL,
    [IsDeleted]   BIT           NULL,
    [Phone]       NVARCHAR (20) NULL,
    [Role]        NVARCHAR (50) NULL,
    [CreatedTime] DATE          NULL,
    [UpdatedTime] DATE          NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[User])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_User] ON;
        INSERT INTO [dbo].[tmp_ms_xx_User] ([Id], [UserName], [Password], [Email], [Status], [IsDeleted], [Phone], [Role], [CreatedTime], [UpdatedTime])
        SELECT   [Id],
                 [UserName],
                 [Password],
                 [Email],
                 [Status],
                 [IsDeleted],
                 [Phone],
                 [Role],
                 [CreatedTime],
                 [UpdatedTime]
        FROM     [dbo].[User]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_User] OFF;
    END

DROP TABLE [dbo].[User];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_User]', N'User';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Creating Foreign Key [dbo].[FK_CV_UngVien]...';


GO
ALTER TABLE [dbo].[CV] WITH NOCHECK
    ADD CONSTRAINT [FK_CV_UngVien] FOREIGN KEY ([UngVienId]) REFERENCES [dbo].[UngVien] ([Id]);


GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[CV] WITH CHECK CHECK CONSTRAINT [FK_CV_UngVien];


GO
PRINT N'Update complete.';


GO
