/*
Deployment script for D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF"
:setvar DefaultFilePrefix "D_\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF_"
:setvar DefaultDataPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering Table [dbo].[CV]...';


GO
ALTER TABLE [dbo].[CV] DROP COLUMN [NgayCapNhat], COLUMN [NgayTao];


GO
ALTER TABLE [dbo].[CV] ALTER COLUMN [CreatedTime] DATETIME NULL;

ALTER TABLE [dbo].[CV] ALTER COLUMN [Ten] NVARCHAR (250) NULL;

ALTER TABLE [dbo].[CV] ALTER COLUMN [UpdatedTime] DATETIME NULL;


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[CV]...';


GO
ALTER TABLE [dbo].[CV]
    ADD DEFAULT 0 FOR [IsDeleted];


GO
PRINT N'Creating Default Constraint unnamed constraint on [dbo].[CV]...';


GO
ALTER TABLE [dbo].[CV]
    ADD DEFAULT GETDATE() FOR [CreatedTime];


GO
PRINT N'Update complete.';


GO
