/*
Deployment script for D:\TIENNHM\FINALPROJECT\FINALPROJECT\DATABASE.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "D:\TIENNHM\FINALPROJECT\FINALPROJECT\DATABASE.MDF"
:setvar DefaultFilePrefix "D_\TIENNHM\FINALPROJECT\FINALPROJECT\DATABASE.MDF_"
:setvar DefaultDataPath "C:\Users\NguyenHuynhMinhTien(\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\"
:setvar DefaultLogPath "C:\Users\NguyenHuynhMinhTien(\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\mssqllocaldb\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Altering Table [dbo].[CV]...';


GO
ALTER TABLE [dbo].[CV]
    ADD [ViTriUngTuyen] NVARCHAR (250) NULL,
        [KyNang]        NVARCHAR (500) NULL,
        [NgoaiNgu]      NVARCHAR (250) NULL,
        [TinHoc]        NVARCHAR (250) NULL,
        [HocVan]        NVARCHAR (500) NULL,
        [HoatDong]      NVARCHAR (500) NULL,
        [ChungChi]      NVARCHAR (500) NULL,
        [MucTieu]       NVARCHAR (500) NULL,
        [KinhNghiem]    NVARCHAR (500) NULL;


GO
PRINT N'Update complete.';


GO
