/*
Deployment script for D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF"
:setvar DefaultFilePrefix "D_\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF_"
:setvar DefaultDataPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Starting rebuilding table [dbo].[CongTy]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_CongTy] (
    [ID]          INT           IDENTITY (1, 1) NOT NULL,
    [Email]       NVARCHAR (50) NULL,
    [TenCongTy]   VARCHAR (200) NULL,
    [DiaChi ]     VARCHAR (200) NULL,
    [TenCEO]      VARCHAR (100) NULL,
    [MST]         VARCHAR (200) NULL,
    [CreatedTime] DATE          NULL,
    [UpdatedTime] DATE          NULL,
    [IsDeleted]   BIT           NULL,
    [UserId]      INT           NULL,
    PRIMARY KEY CLUSTERED ([ID] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[CongTy])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_CongTy] ON;
        INSERT INTO [dbo].[tmp_ms_xx_CongTy] ([ID], [Email], [TenCongTy], [DiaChi ], [TenCEO], [MST], [CreatedTime], [UpdatedTime], [IsDeleted], [UserId])
        SELECT   [ID],
                 [Email],
                 [TenCongTy],
                 [DiaChi ],
                 [TenCEO],
                 [MST],
                 [CreatedTime],
                 [UpdatedTime],
                 [IsDeleted],
                 [UserId]
        FROM     [dbo].[CongTy]
        ORDER BY [ID] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_CongTy] OFF;
    END

DROP TABLE [dbo].[CongTy];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_CongTy]', N'CongTy';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Update complete.';


GO
