/*
Deployment script for D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "D:\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF"
:setvar DefaultFilePrefix "D_\REPOS\FINALPROJECT\FINALPROJECT\DATABASE.MDF_"
:setvar DefaultDataPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"
:setvar DefaultLogPath "C:\Users\tiennhm\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\MSSQLLocalDB\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename [dbo].[UngTuyen].[UpdatedTime] to ThoiGianPhongVan';


GO
EXECUTE sp_rename @objname = N'[dbo].[UngTuyen].[UpdatedTime]', @newname = N'ThoiGianPhongVan', @objtype = N'COLUMN';


GO
PRINT N'Rename refactoring operation with key  is skipped, element [dbo].[UngTuyen].[KetQuaPhongVan] (SqlSimpleColumn) will not be renamed to DiaDiemPhongVan';


GO
PRINT N'Starting rebuilding table [dbo].[UngTuyen]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_UngTuyen] (
    [Id]               INT            IDENTITY (1, 1) NOT NULL,
    [CongViecId]       INT            NULL,
    [UngVienId]        INT            NULL,
    [CvId]             INT            NULL,
    [TrangThai]        NVARCHAR (50)  NULL,
    [MoTa]             NVARCHAR (200) NULL,
    [IsDeleted]        BIT            NULL,
    [CreatedTime]      DATE           DEFAULT getdate() NULL,
    [UpdatedTime]      DATE           NULL,
    [ThoiGianPhongVan] DATE           NULL,
    [DiaDiemPhongVan]  NVARCHAR (200) NULL,
    [NguoiPhongVan]    NVARCHAR (50)  NULL,
    [KetQuaPhongVan]   NVARCHAR (200) NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[UngTuyen])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_UngTuyen] ON;
        INSERT INTO [dbo].[tmp_ms_xx_UngTuyen] ([Id], [CongViecId], [UngVienId], [CvId], [TrangThai], [MoTa], [IsDeleted], [CreatedTime], [ThoiGianPhongVan])
        SELECT   [Id],
                 [CongViecId],
                 [UngVienId],
                 [CvId],
                 [TrangThai],
                 [MoTa],
                 [IsDeleted],
                 [CreatedTime],
                 [ThoiGianPhongVan]
        FROM     [dbo].[UngTuyen]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_UngTuyen] OFF;
    END

DROP TABLE [dbo].[UngTuyen];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_UngTuyen]', N'UngTuyen';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Update complete.';


GO
